# Generated by Django 6.0 on 2026-01-06 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tramite', models.CharField(choices=[('vehicular', 'Vehicular'), ('sat', 'SAT'), ('acta', 'Acta de nacimiento'), ('antecedentes', 'Antecedentes no penales'), ('nss', 'Número de seguridad social'), ('vigencia', 'Vigencia de derechos')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=18)),
                ('correo', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=15)),
                ('datos_extra', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
